spring.application.name=demo

# Configuracoes do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/geekbay_db
spring.datasource.username=admin_geekbay
spring.datasource.password=senhaAdmin123

# Configuracoes do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracoes do Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration